### ISSUE TITLE
revenu fiscal de référence == 0

### ISSUE THREAD

**Issue by sirignano** [betagouv/svair-mock#11]
Bonjour,

Lorsque je cherche une personne avec :  
- numéro fiscal : 1782453447252
- référence avis : 1769051442252

J'ai un résultat vide sur 
  "revenuBrutGlobal": 0,
  "revenuImposable": 0,
  "impotRevenuNetAvantCorrections": 0,
  "montantImpot": 0,
  "revenuFiscalReference": 0

Au lieu des chiffres présents dans MyData.csv

**Comment by annemarie35** [comment]
Bonjour Lucas,

Le problème semble encore venir du fait que le fichier https://raw.githubusercontent.com/betagouv/svair-mock/master/data/myData.csv ne soit pas encodé en UTF8
