### ISSUE TITLE
Encodage

### ISSUE THREAD

**Issue by sirignano** [betagouv/svair-mock#12]
Bonjour,

pour les info : 1782453447251+1769051442251

J'ai une réponse en addresse : 3 Rue Jean Jaurès 25500 Morteau

Avec un "nom": "L�vesque"

N'y a t'il pas un problème d'encodage dans votre bdd ?

si ce n'est pas le cas comment sont il encodé ?

**Comment by annemarie35** [comment]
Bonjour Lucas,

Il semblerait que le CVS ne soit pas encodé en UTF8 https://raw.githubusercontent.com/betagouv/svair-mock/b9a8cde1ea36a6933530e7f8ac31c2bb3538925d/data/myData.csv

Je te propose de refaire une PR avec le fichier encodé au bon format.
